[general]
    save-window-states = true # Saves and restores the position and current tab of all windows
    global_font = 'B612' # 'B612', and 'Iosevka Aile' are built-in
    global-hotkeys = false
    [[window]] # Defines new window
        enabled = true
        align = 'North'
        [[window.widget]] # Defines new widget
            type = 'intake' # Defines widget type
            base-lock = false
        [[window.widget]]
            type = 'swerve'
        [[window.widget]]
            type = 'status'
        [[window.widget]]
            type = 'lift'
    
    [[window]]
        [[window.widget]]
            type = 'reef'
        [[window.widget]]
            type = 'status'

[network]
    address = "localhost" # Use either IP address or team number
    ds-client = false # no clue what this does lmao

[tabs] # Default settings for tabs
    global-hotkeys = false # Enables tab switching via hotkeys when the window is not focused
    align = 'South' # Align tab bar to either 'North', 'East', 'South', or 'West'

[status] # Default settings for Status widgets
    enable-scroll = true # Enables vertical scrolling through the widget
    blink-interval = 0.2 # Time in seconds for each blink cycle. Set to 0 to disable blinking
    network-table = "FMSInfo"

[swerve] # Default settings for Swerve widgets
    base-lock = false # Locks base to single rotation
    wheel-lock = false # Locks wheels to single rotation
    base-table = "tracking"
    wheel-table = "swerve"

[lift] # Default settings for Lift widgets
    network-table = "lift"

[intake] # Default settings for Intake widgets
    network-table = "intake"

[reef] # Default settings for Reef widgets
    # aint nothing here lmao