[general]
    save-window-states = true # Saves and restores the position, size, and current tab of all windows
    show-unused-widgets = false # Temporary option in place until all widgets are fully supported by NetworkTables
    global_font = 'B612' # 'B612', and 'Iosevka Aile' are built-in
    global-hotkeys = false
    [[window]] # Defines new window
        enabled = true
        [[window.widget]] # Defines new widget
            type = "faults" # Defines widget type
    [[window]]
        [[window.widget]]
            type = "swerve"
    [[window]]
        [[window.widget]]
            type = 'lift'
    [[window]]
        [[window.widget]]
            type = 'intake'
    
    [[window]]
        [[window.widget]]
            type = 'reef'

[network]
    address = "localhost" # Use either IP address or team number
    ds-client = false # no clue what this does lmao

[tabs] # Default settings for tabs
    global-hotkeys = false # Enables tab switching via hotkeys when the window is not focused
    align = "North" # Align tab bar to either 'North', 'East', 'South', or 'West'

[faults] # Default settings for fault manager widgets
    enable-scroll = true # Enables vertical scrolling through the widget
    hide-if-empty = true
    network-table = "SmartDashboard"
    [[faults.fault_list]]
        name = "Intake"
        fault = "fm_intake_faults"
    [[faults.fault_list]]
        name = "Lift"
        fault = "fm_lift_faults"
    [[faults.fault_list]]
        name = "Driver Input"
        fault = "fm_DriverInput_faults"
    [[faults.fault_list]]
        name = "Operator Input"
        fault = "fm_OperatorInput_faults"
    [[faults.fault_list]]
        name = "SMC 1"
        fault = "fm_SMC1_faults"
    [[faults.fault_list]]
        name = "SMC 2"
        fault = "fm_SMC2_faults"
    [[faults.fault_list]]
        name = "SMC 3"
        fault = "fm_SMC3_faults"
    [[faults.fault_list]]
        name = "SMC 4"
        fault = "fm_SMC4_faults"
    [[faults.fault_list]]
        name = "Auto Pilot"
        fault = "fm_AutoPilot_faults"

[swerve] # Default settings for sweerve widgets
    base-lock = false # Locks base to single rotation
    wheel-lock = false # Locks wheels to single rotation
    base-table = "tracking"
    wheel-table = "swerve"
    faults-table = ["fm_SMC1_faults", "fm_SMC2_faults", "fm_SMC3_faults", "fm_SMC4_faults"]

[lift] # Default settings for lift widgets
    network-table = "lift"
    gripper-table = "SmartDashboard"
    faults-table = ["fm_lift_faults"]

[intake] # Default settings for intake widgets
    network-table = "intake"
    faults-table = ["fm_intake_faults"]

[reef] # Default settings for reef widgets
    network-table = "SmartDashboard"